language: python

python:
  - pypy3
  - pypy
  - 3.6
  - 3.5
  - 3.4
  - 2.7

sudo: false

install:
  - travis_retry pip install coverage
  - travis_retry python setup.py install

script:
  - coverage run --include=pycorpora/* tests/test_pycorpora.py

after_success:
    # Report coverage and send to coveralls.io
  - coverage report
  - pip install coveralls && coveralls

    # Static analysis
  - travis_retry pip install pep8 pyflakes
  - pep8 --statistics --count *.py
  - pep8 --statistics --count pycorpora/*.py
  - pep8 --statistics --count tests/*.py
  - pyflakes *.py           | tee >(wc -l)
  - pyflakes pycorpora/*.py | tee >(wc -l)
  - pyflakes tests/*.py     | tee >(wc -l)


matrix:
  fast_finish: true
